on: [push, pull_request]

jobs: 
  diff:
    runs-on: ubuntu-latest
    name: git diff
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        uses: technote-space/get-diff-action@v6
    outputs:
      CHANGED_FILE: ${{ steps.diff.outputs.diff }}

  lint-check:
    needs: diff
    runs-on: ubuntu-latest
    container: 
      image: kusionstack/kusion:latest
      env: 
        CHANGED_FILE: ${{needs.diff.outputs.CHANGED_FILE}}
    steps:
      - uses: actions/checkout@v2
      - id: install-pytest-html
        run: kclvm -mpip install pytest-html -i http://mirrors.aliyun.com/pypi/simple/
      - id: lint-check
        run: |
          export KCL_TEST_MODE="base"
          kclvm -mpytest -v -n 5 hack/lint_check.py --junitxml ./hack/report/lint-check.xml --html=./hack/report/lint.html
      - id: upload-lint-check-report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lint-check-report
          path: |
            hack/report/lint-check.xml
            hack/report/lint.html
